import Header from "@/components/Header/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/context/AuthContext";
import LoaderWrapper from "@/components/LoaderWrapper";

export const metadata = {
  title: "Next Social Network",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body
        className={
          "antialiased bg-neutral-900 min-h-screen flex flex-col"
        }
      >
        <AuthProvider>
          <LoaderWrapper>
            <Header />
            <div className="flex-grow px-4 md:px-0 container mx-auto">
              {children}
            </div>
            <Footer />
          </LoaderWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
